/*
* generated by Xtext
*/
package de.jax.heim.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.jax.heim.services.RegelspracheGrammarAccess;

public class RegelspracheParser extends AbstractContentAssistParser {
	
	@Inject
	private RegelspracheGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.jax.heim.ui.contentassist.antlr.internal.InternalRegelspracheParser createParser() {
		de.jax.heim.ui.contentassist.antlr.internal.InternalRegelspracheParser result = new de.jax.heim.ui.contentassist.antlr.internal.InternalRegelspracheParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDeklarationAccess().getAlternatives(), "rule__Deklaration__Alternatives");
					put(grammarAccess.getGeraetAccess().getGroup(), "rule__Geraet__Group__0");
					put(grammarAccess.getGeraetAccess().getGroup_2(), "rule__Geraet__Group_2__0");
					put(grammarAccess.getGeraetAccess().getGroup_2_1(), "rule__Geraet__Group_2_1__0");
					put(grammarAccess.getRegelAccess().getGroup(), "rule__Regel__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getModelAccess().getDeklarationenAssignment(), "rule__Model__DeklarationenAssignment");
					put(grammarAccess.getGeraetAccess().getNameAssignment_0(), "rule__Geraet__NameAssignment_0");
					put(grammarAccess.getGeraetAccess().getZustaendeAssignment_2_0(), "rule__Geraet__ZustaendeAssignment_2_0");
					put(grammarAccess.getGeraetAccess().getZustaendeAssignment_2_1_1(), "rule__Geraet__ZustaendeAssignment_2_1_1");
					put(grammarAccess.getZustandAccess().getNameAssignment(), "rule__Zustand__NameAssignment");
					put(grammarAccess.getRegelAccess().getWennAssignment_1(), "rule__Regel__WennAssignment_1");
					put(grammarAccess.getRegelAccess().getDannAssignment_3(), "rule__Regel__DannAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.jax.heim.ui.contentassist.antlr.internal.InternalRegelspracheParser typedParser = (de.jax.heim.ui.contentassist.antlr.internal.InternalRegelspracheParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RegelspracheGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RegelspracheGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
