/*
* generated by Xtext
*/
package de.jax.heim.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RegelspracheAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/jax/heim/parser/antlr/internal/InternalRegelsprache.tokens");
	}
}
