/*
* generated by Xtext
*/
package de.jax.smarthome;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RegelSpracheStandaloneSetup extends RegelSpracheStandaloneSetupGenerated{

	public static void doSetup() {
		new RegelSpracheStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

