/*
 * generated by Xtext
 */
package de.jax.smarthome;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RegelSpracheRuntimeModule extends de.jax.smarthome.AbstractRegelSpracheRuntimeModule {

}
