/*
 * generated by Xtext
 */
package de.jax.smarthome.validation

import org.eclipse.xtext.validation.Check
import de.jax.smarthome.regelSprache.Regel
import de.jax.smarthome.regelSprache.RegelSprachePackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class RegelSpracheValidator extends AbstractRegelSpracheValidator {

	public static val FALSCHER_ARTIKEL = 'falscher.artikel'

	@Check
	def checkGeraetArtikel(Regel regel) {
		if (regel.wennGeraet.artikel.toLowerCase != regel.wennArtikel) {
			error('Falscher Artikel "'+regel.wennArtikel+'"', 
					RegelSprachePackage.Literals.REGEL__WENN_ARTIKEL,
					FALSCHER_ARTIKEL)
		}
		if (regel.dannGeraet.artikel.toLowerCase != regel.dannArtikel) {
			error('Falscher Artikel "'+regel.dannArtikel+'"', 
					RegelSprachePackage.Literals.REGEL__DANN_ARTIKEL,
					FALSCHER_ARTIKEL)
		}
	}
}
