/*
 * generated by Xtext
 */
package de.jax.heim;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RegelspracheRuntimeModule extends de.jax.heim.AbstractRegelspracheRuntimeModule {

}
