grammar de.jax.heim.Regelsprache with org.eclipse.xtext.common.Terminals

generate regelsprache "http://www.jax.de/heim/Regelsprache"

Model:
	deklarationen+=Deklaration*;
	
Deklaration :
	Regel | Geraet
;

Geraet:
	name=ID 'kann' (zustaende+=Zustand (',' zustaende+=Zustand)*)?
;

Zustand:
	name=ID
;

Regel:
	'Wenn' wenn=[Zustand | QualifiedName] 'dann' dann=[Zustand | QualifiedName]
;

QualifiedName :
	ID ('.' ID)*
; 

