/*
* generated by Xtext
*/
package de.jax.heim;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RegelspracheStandaloneSetup extends RegelspracheStandaloneSetupGenerated{

	public static void doSetup() {
		new RegelspracheStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

