/**
 * generated by Xtext
 */
package de.jax.smarthome.validation;

import com.google.common.base.Objects;
import de.jax.smarthome.regelSprache.Geraet;
import de.jax.smarthome.regelSprache.Regel;
import de.jax.smarthome.regelSprache.RegelSprachePackage;
import de.jax.smarthome.validation.AbstractRegelSpracheValidator;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RegelSpracheValidator extends AbstractRegelSpracheValidator {
  public final static String FALSCHER_ARTIKEL = "falscher.artikel";
  
  @Check
  public void checkGeraetArtikel(final Regel regel) {
    Geraet _wennGeraet = regel.getWennGeraet();
    String _artikel = _wennGeraet.getArtikel();
    String _lowerCase = _artikel.toLowerCase();
    String _wennArtikel = regel.getWennArtikel();
    boolean _notEquals = (!Objects.equal(_lowerCase, _wennArtikel));
    if (_notEquals) {
      String _wennArtikel_1 = regel.getWennArtikel();
      String _plus = ("Falscher Artikel \"" + _wennArtikel_1);
      String _plus_1 = (_plus + "\"");
      this.error(_plus_1, 
        RegelSprachePackage.Literals.REGEL__WENN_ARTIKEL, 
        RegelSpracheValidator.FALSCHER_ARTIKEL);
    }
    Geraet _dannGeraet = regel.getDannGeraet();
    String _artikel_1 = _dannGeraet.getArtikel();
    String _lowerCase_1 = _artikel_1.toLowerCase();
    String _dannArtikel = regel.getDannArtikel();
    boolean _notEquals_1 = (!Objects.equal(_lowerCase_1, _dannArtikel));
    if (_notEquals_1) {
      String _dannArtikel_1 = regel.getDannArtikel();
      String _plus_2 = ("Falscher Artikel \"" + _dannArtikel_1);
      String _plus_3 = (_plus_2 + "\"");
      this.error(_plus_3, 
        RegelSprachePackage.Literals.REGEL__DANN_ARTIKEL, 
        RegelSpracheValidator.FALSCHER_ARTIKEL);
    }
  }
}
