/*
 * generated by Xtext
 */
package de.jax.smarthome.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.jax.smarthome.ui.internal.RegelSpracheActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RegelSpracheExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RegelSpracheActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RegelSpracheActivator.getInstance().getInjector(RegelSpracheActivator.DE_JAX_SMARTHOME_REGELSPRACHE);
	}
	
}
