/*
 * generated by Xtext
 */
package de.jax.heim.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RegelspracheUiModule extends de.jax.heim.ui.AbstractRegelspracheUiModule {
	public RegelspracheUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
