/**
 * generated by Xtext
 */
package de.jax.heim.validation;

import de.jax.heim.validation.AbstractRegelspracheValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RegelspracheValidator extends AbstractRegelspracheValidator {
}
