/*
* generated by Xtext
*/
package de.jax.smarthome.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RegelSpracheAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/jax/smarthome/parser/antlr/internal/InternalRegelSprache.tokens");
	}
}
