/*
* generated by Xtext
*/
package de.jax.smarthome.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.jax.smarthome.services.RegelSpracheGrammarAccess;

public class RegelSpracheParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RegelSpracheGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.jax.smarthome.parser.antlr.internal.InternalRegelSpracheParser createParser(XtextTokenStream stream) {
		return new de.jax.smarthome.parser.antlr.internal.InternalRegelSpracheParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public RegelSpracheGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RegelSpracheGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
