/*
* generated by Xtext
*/
package de.jax.smarthome;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RegelSpracheUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.jax.smarthome.ui.internal.RegelSpracheActivator.getInstance().getInjector("de.jax.smarthome.RegelSprache");
	}
	
}
