/*
* generated by Xtext
*/
package de.jax.heim;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RegelspracheUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.jax.heim.ui.internal.RegelspracheActivator.getInstance().getInjector("de.jax.heim.Regelsprache");
	}
	
}
