/**
 * generated by Xtext
 */
package de.jax.smarthome.ui.contentassist;

import de.jax.smarthome.ui.contentassist.AbstractRegelSpracheProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class RegelSpracheProposalProvider extends AbstractRegelSpracheProposalProvider {
}
