/*
 * generated by Xtext
 */
package de.jax.heim.ui.contentassist

import de.jax.heim.ui.contentassist.AbstractRegelspracheProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RegelspracheProposalProvider extends AbstractRegelspracheProposalProvider {
}
