/*
 * generated by Xtext
 */
package de.jax.smarthome.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRegelSpracheValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.jax.smarthome.regelSprache.RegelSprachePackage.eINSTANCE);
		return result;
	}
}
