/**
 * generated by Xtext
 */
package de.jax.smarthome.ui.labeling;

import com.google.inject.Inject;
import de.jax.smarthome.regelSprache.Geraet;
import de.jax.smarthome.regelSprache.Regel;
import de.jax.smarthome.regelSprache.Zustand;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class RegelSpracheLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public RegelSpracheLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Regel ele) {
    Geraet _wennGeraet = ele.getWennGeraet();
    String _name = _wennGeraet.getName();
    String _plus = ("Wenn " + _name);
    String _plus_1 = (_plus + " ");
    Zustand _wenn = ele.getWenn();
    String _name_1 = _wenn.getName();
    return (_plus_1 + _name_1);
  }
  
  public String text(final Geraet it) {
    String _artikel = it.getArtikel();
    String _plus = (_artikel + " ");
    String _name = it.getName();
    return (_plus + _name);
  }
  
  public String text(final Zustand it) {
    return it.getName();
  }
}
