/*
 * generated by Xtext
 */
package de.jax.smarthome.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RegelSpracheUiModule extends de.jax.smarthome.ui.AbstractRegelSpracheUiModule {
	public RegelSpracheUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
