/*
 * generated by Xtext
 */
package de.jax.heim.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRegelspracheValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.jax.heim.regelsprache.RegelsprachePackage.eINSTANCE);
		return result;
	}
}
